// <auto-generated />
using System;
using Harvester.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Harvester.Infrastructure.Migrations
{
    [DbContext(typeof(HarvesterDbContext))]
    [Migration("20251001183252_IsArchivedForOrder")]
    partial class IsArchivedForOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Harvester.Domain.Models.Combine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvailableWorkHours")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("BaseEfficency")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(0.75m);

                    b.Property<decimal>("BaseHaPerHour")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(1m);

                    b.Property<bool>("HasStrawChopper")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("HeaderLength")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PricePerHectare")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Combines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableWorkHours = 11m,
                            BaseEfficency = 0.75m,
                            BaseHaPerHour = 2.5m,
                            HasStrawChopper = false,
                            HeaderLength = 6m,
                            IsAvailable = true,
                            IsDeleted = false,
                            Model = "John Deere X1",
                            PricePerHectare = 600
                        },
                        new
                        {
                            Id = 2,
                            AvailableWorkHours = 11m,
                            BaseEfficency = 0.75m,
                            BaseHaPerHour = 3.0m,
                            HasStrawChopper = false,
                            HeaderLength = 7m,
                            IsAvailable = true,
                            IsDeleted = false,
                            Model = "Case IH 8230",
                            PricePerHectare = 550
                        });
                });

            modelBuilder.Entity("Harvester.Domain.Models.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaHectares")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<MultiPolygon>("Boundary")
                        .HasColumnType("geometry");

                    b.Property<Point>("CenterPoint")
                        .HasColumnType("geometry");

                    b.Property<string>("CommonName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CropType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdentifierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("ShapeCoeff")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(1m);

                    b.Property<decimal>("TerrainCoeff")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(1m);

                    b.HasKey("Id");

                    b.ToTable("Fields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaHectares = 10.5m,
                            CropType = "Wheat",
                            IdentifierName = "Pole A",
                            IsDeleted = false,
                            ShapeCoeff = 1.0m,
                            TerrainCoeff = 1.0m
                        },
                        new
                        {
                            Id = 2,
                            AreaHectares = 8.2m,
                            CropType = "Corn",
                            IdentifierName = "Pole B",
                            IsDeleted = false,
                            ShapeCoeff = 1.0m,
                            TerrainCoeff = 0.9m
                        });
                });

            modelBuilder.Entity("Harvester.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CombineId")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedPrice")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("int");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrawProcessingMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("CombineId");

                    b.HasIndex("FieldId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CombineId = 1,
                            EstimatedPrice = 0m,
                            EstimatedTime = 0,
                            FieldId = 1,
                            IsArchived = false,
                            IsDeleted = false,
                            OrderDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "ACCEPTED",
                            StrawProcessingMethod = "LEAVE",
                            TotalPrice = 1575.0m
                        },
                        new
                        {
                            Id = 2,
                            CombineId = 2,
                            EstimatedPrice = 0m,
                            EstimatedTime = 0,
                            FieldId = 2,
                            IsArchived = false,
                            IsDeleted = false,
                            OrderDate = new DateTime(2025, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateTime(2025, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "PENDING",
                            StrawProcessingMethod = "CHOP",
                            TotalPrice = 1148.0m
                        });
                });

            modelBuilder.Entity("Harvester.Domain.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Harvester.Domain.Models.Order", b =>
                {
                    b.HasOne("Harvester.Domain.Models.Combine", "Combine")
                        .WithMany("Orders")
                        .HasForeignKey("CombineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Harvester.Domain.Models.Field", "Field")
                        .WithMany("Orders")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combine");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("Harvester.Domain.Models.Payment", b =>
                {
                    b.HasOne("Harvester.Domain.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Harvester.Domain.Models.Combine", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Harvester.Domain.Models.Field", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Harvester.Domain.Models.Order", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
